#!/usr/bin/env bash
# Generate skill-bank catalogs from upstream. For each sources.yml entry whose
# `enumerate:` is not '-', list its skill subdirectories, fetch each SKILL.md, and
# write references/skill-bank/catalog/<key>.md (header + table). The table body is
# produced by scripts/format_catalog.sh (unit-tested); this script is the network
# adapter (uses gh + curl) and is not unit-tested. An enumerate of '.' means the repo
# root. Run: bash scripts/build_skill_bank_catalog.sh
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
SOURCES="$ROOT/references/skill-bank/sources.yml"
OUTDIR="$ROOT/references/skill-bank/catalog"
FORMAT="$HERE/format_catalog.sh"
TODAY="$(date +%F)"

command -v gh >/dev/null 2>&1 || { echo "build: gh CLI required" >&2; exit 2; }
mkdir -p "$OUTDIR"

unquote() { local s="$1"; s="${s%\"}"; s="${s#\"}"; printf '%s' "$s"; }

awk '
  /^- key:/ {
    if (key!="") print key"|"repo"|"enum"|"ref
    key=$3; repo=""; enum="-"; ref="main"
  }
  /^[[:space:]]+repo:/      { repo=$2 }
  /^[[:space:]]+enumerate:/ { line=$0; sub(/^[[:space:]]*enumerate:[[:space:]]*/,"",line); sub(/[[:space:]]+#.*$/,"",line); sub(/[[:space:]]+$/,"",line); enum=line }
  /^[[:space:]]+ref:/       { ref=$2 }
  END { if (key!="") print key"|"repo"|"enum"|"ref }
' "$SOURCES" | while IFS='|' read -r key repo enum ref; do
  key="$(unquote "$key")"; repo="$(unquote "$repo")"; enum="$(unquote "$enum")"; ref="$(unquote "$ref")"
  [ -z "$ref" ] && ref="main"
  [ "$enum" = "-" ] && { echo "skip $key (enumerate: -)"; continue; }
  ownerrepo="${repo#https://github.com/}"; ownerrepo="${ownerrepo%/}"
  set -f; paths=( $enum ); set +f
  multi=0; [ "${#paths[@]}" -gt 1 ] && multi=1
  echo "building $key from $ownerrepo (enumerate: $enum, ref: $ref) ..."
  infile="$(mktemp)"
  for p in "${paths[@]}"; do
    if [ "$p" = "." ]; then
      apipath="contents"; rawprefix=""; slugprefix=""
    else
      apipath="contents/$p"; rawprefix="$p/"
      if [ "$multi" -eq 1 ]; then slugprefix="${p%%/*}/"; else slugprefix=""; fi
    fi
    tmplist="$(mktemp)"
    if ! gh api "repos/$ownerrepo/$apipath?ref=$ref" \
          --jq '.[] | select(.type=="dir") | .name' > "$tmplist" 2>/dev/null; then
      echo "  WARN: could not list $ownerrepo/$p (ref $ref) — skipping path" >&2
      rm -f "$tmplist"; continue
    fi
    while IFS= read -r slug; do
      [ -z "$slug" ] && continue
      sk="$(mktemp)"
      if curl -fsSL "https://raw.githubusercontent.com/$ownerrepo/$ref/${rawprefix}${slug}/SKILL.md" -o "$sk" 2>/dev/null; then
        printf '%s:%s\t%s\n' "$key" "${slugprefix}${slug}" "$sk" >> "$infile"
      else
        rm -f "$sk"
      fi
    done < "$tmplist"
    rm -f "$tmplist"
  done
  if [ ! -s "$infile" ]; then
    echo "  WARN: no SKILL.md found for $key (ref $ref) — skipping $key" >&2
    rm -f "$infile"; continue
  fi
  {
    echo "# $key — full catalog (auto-generated by scripts/build_skill_bank_catalog.sh; do not hand-edit)"
    echo "# source: $repo · synced: $ownerrepo@$ref $TODAY"
    echo
    bash "$FORMAT" < "$infile"
  } > "$OUTDIR/$key.md"
  echo "  wrote catalog/$key.md"
  cut -f2 "$infile" | xargs -r rm -f
  rm -f "$infile"
done
echo "done."
